language: python
matrix:
  include:
  - python: 3.8
    env: TOXENV=flake8
install:
- pip install tox
script:
- tox
deploy:
  skip_cleanup: true
  provider: pypi
  user: __token__
  password:
    secure: ZEsM76obFP9ZIGdHkKIgMFc/7qN33ZCO/2Tl0E8noUOHuL/dPkKeG1VWD7XiXupljULgRkxKInrz5aw/423+qwy1kQw2rDxdxbs4ITAbp3xEd4X7N2WwvYp7biuw5z4I2lzY7TI6HvHxFeN25Wvo1qIc7SIMMcYmSAY7pOs7qW+ljfrg9PhBJZBk0zZ3ISAu8npkIVa9FKaYTbx0lq9GWdy3bovkGER4DwcjGB6Cx0OCSrLxwYqNi34xlSy7hBQugQp85SqSlwOpgxLGgxr0/xyW73iQdoQhcFdl3Aoupudu/suy0w7JShANGeD2cWtXs5a028w79tKwKmlb11gSFbLT9fdhxdSPU87qm5EOye0loCg5pGQtZvZ2Zf+WyIFaPWl7UewcBDHNSx2APUHokpI9N6qoaI94CcY5UHCmlXGc2PMN00WmhTlHGYsFEADoFa5brqBNEvP5XpHa8eT/w63tGG/v/a9NdfLMzktYemUIGdNZrOj8V1YGjd28HsxE2/zF/kG9Qbq1878tYmocpxro8gQXdbzc1DyiXZsyDWPRSv7WCIXl07Y2nWIqKuuQmmrFlxTw+SmRiIXpzl2YZ2c5UqPJFNcaJ5fZ2U+MwadbkhuANIYn5vc4AkZyz2L/jeyKz7wNB7Ar8DgAKxKkZ0gJv7AICZTGEXXEtIeMsdk=
  skip_existing: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME = linux"
