language: python

matrix:
  include:
    - python: 3.8
      os: linux
      dist: xenial
      sudo: true

before_install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

install:
  - poetry install
  
script:
  - poetry run pylint tilingsgui/
  - poetry run flake8 tilingsgui/
  - poetry run mypy tilingsgui
  - poetry run pytest